### ISSUE TITLE
Which branch of EpubJS will we use?

### ISSUE THREAD

**Issue by msimmer** [triplecanopy/b-ber-boiler#10]
I was just looking through the epubjs repo, it seems like the latest dev branch ([v0.3](https://github.com/futurepress/epub.js/tree/v0.3)) will be merged into master soon(-ish), and there are a number of breaking changes in the update.  

i think i'd opt for using the development version, maybe we could also dovetail our own development with their release, i.e. contributing to the epubjs repo as we encounter issues.

it's hard to know exactly what their timeline is like, but making up a roadmap is being tracked [here](https://github.com/futurepress/epub.js/issues/471), so maybe we get a better sense in the next week or two

**Comment by srerickson** [comment]
we are using the v0.3 version right now, which is still in development.
